package Generation.Exilegames;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Date;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private usuariosRepositorio usuariosRepositorio;
    private videojuegosRepositorio videojuegosRepositorio;


    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUserio (
            @RequestParam String nombre,
            @RequestParam String apellido,
            @RequestParam String correo,
            @RequestParam String contrasena,
            //@RequestParam Date fechanac,
            @RequestParam Integer rol)
            {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        usuarios n = new usuarios();
        n.setNombre(nombre);
        n.setApellido(apellido);
        n.setCorreo(correo);
        n.setContrasena(contrasena);
       // n.setFechanac(fechanac);
        n.setRol(rol);
        usuariosRepositorio.save(n);
        return "Se guardaron los datos";
    }



    @GetMapping(path="/all")
    public @ResponseBody Iterable<usuarios> getAllUsers() {
        // This returns a JSON or XML with the users
        return usuariosRepositorio.findAll();
    }
}

